// Curated list of ~120 major world cities for birthplace selection.
// Each entry carries an English + Chinese label so the picker works in both languages.
export type City = {
  en: string;
  zh: string;
  country: string;
  countryZh: string;
};

export const CITIES: City[] = [
  { en: "Beijing", zh: "北京", country: "China", countryZh: "中国" },
  { en: "Shanghai", zh: "上海", country: "China", countryZh: "中国" },
  { en: "Guangzhou", zh: "广州", country: "China", countryZh: "中国" },
  { en: "Shenzhen", zh: "深圳", country: "China", countryZh: "中国" },
  { en: "Chengdu", zh: "成都", country: "China", countryZh: "中国" },
  { en: "Hangzhou", zh: "杭州", country: "China", countryZh: "中国" },
  { en: "Nanjing", zh: "南京", country: "China", countryZh: "中国" },
  { en: "Xi'an", zh: "西安", country: "China", countryZh: "中国" },
  { en: "Wuhan", zh: "武汉", country: "China", countryZh: "中国" },
  { en: "Chongqing", zh: "重庆", country: "China", countryZh: "中国" },
  { en: "Tianjin", zh: "天津", country: "China", countryZh: "中国" },
  { en: "Suzhou", zh: "苏州", country: "China", countryZh: "中国" },
  { en: "Qingdao", zh: "青岛", country: "China", countryZh: "中国" },
  { en: "Dalian", zh: "大连", country: "China", countryZh: "中国" },
  { en: "Xiamen", zh: "厦门", country: "China", countryZh: "中国" },
  { en: "Kunming", zh: "昆明", country: "China", countryZh: "中国" },
  { en: "Changsha", zh: "长沙", country: "China", countryZh: "中国" },
  { en: "Harbin", zh: "哈尔滨", country: "China", countryZh: "中国" },
  { en: "Shenyang", zh: "沈阳", country: "China", countryZh: "中国" },
  { en: "Lhasa", zh: "拉萨", country: "China", countryZh: "中国" },
  { en: "Hong Kong", zh: "香港", country: "China", countryZh: "中国" },
  { en: "Macau", zh: "澳门", country: "China", countryZh: "中国" },
  { en: "Taipei", zh: "台北", country: "Taiwan", countryZh: "台湾" },
  { en: "Kaohsiung", zh: "高雄", country: "Taiwan", countryZh: "台湾" },
  { en: "Tokyo", zh: "东京", country: "Japan", countryZh: "日本" },
  { en: "Osaka", zh: "大阪", country: "Japan", countryZh: "日本" },
  { en: "Kyoto", zh: "京都", country: "Japan", countryZh: "日本" },
  { en: "Sapporo", zh: "札幌", country: "Japan", countryZh: "日本" },
  { en: "Fukuoka", zh: "福冈", country: "Japan", countryZh: "日本" },
  { en: "Seoul", zh: "首尔", country: "South Korea", countryZh: "韩国" },
  { en: "Busan", zh: "釜山", country: "South Korea", countryZh: "韩国" },
  { en: "Singapore", zh: "新加坡", country: "Singapore", countryZh: "新加坡" },
  { en: "Kuala Lumpur", zh: "吉隆坡", country: "Malaysia", countryZh: "马来西亚" },
  { en: "Bangkok", zh: "曼谷", country: "Thailand", countryZh: "泰国" },
  { en: "Jakarta", zh: "雅加达", country: "Indonesia", countryZh: "印度尼西亚" },
  { en: "Manila", zh: "马尼拉", country: "Philippines", countryZh: "菲律宾" },
  { en: "Hanoi", zh: "河内", country: "Vietnam", countryZh: "越南" },
  { en: "Ho Chi Minh City", zh: "胡志明市", country: "Vietnam", countryZh: "越南" },
  { en: "Mumbai", zh: "孟买", country: "India", countryZh: "印度" },
  { en: "Delhi", zh: "德里", country: "India", countryZh: "印度" },
  { en: "Bengaluru", zh: "班加罗尔", country: "India", countryZh: "印度" },
  { en: "Chennai", zh: "钦奈", country: "India", countryZh: "印度" },
  { en: "Kolkata", zh: "加尔各答", country: "India", countryZh: "印度" },
  { en: "Hyderabad", zh: "海得拉巴", country: "India", countryZh: "印度" },
  { en: "Karachi", zh: "卡拉奇", country: "Pakistan", countryZh: "巴基斯坦" },
  { en: "Dhaka", zh: "达卡", country: "Bangladesh", countryZh: "孟加拉国" },
  { en: "Colombo", zh: "科伦坡", country: "Sri Lanka", countryZh: "斯里兰卡" },
  { en: "Kathmandu", zh: "加德满都", country: "Nepal", countryZh: "尼泊尔" },
  { en: "Dubai", zh: "迪拜", country: "UAE", countryZh: "阿联酋" },
  { en: "Abu Dhabi", zh: "阿布扎比", country: "UAE", countryZh: "阿联酋" },
  { en: "Riyadh", zh: "利雅得", country: "Saudi Arabia", countryZh: "沙特阿拉伯" },
  { en: "Tehran", zh: "德黑兰", country: "Iran", countryZh: "伊朗" },
  { en: "Istanbul", zh: "伊斯坦布尔", country: "Turkey", countryZh: "土耳其" },
  { en: "Jerusalem", zh: "耶路撒冷", country: "Israel", countryZh: "以色列" },
  { en: "Tel Aviv", zh: "特拉维夫", country: "Israel", countryZh: "以色列" },
  { en: "Cairo", zh: "开罗", country: "Egypt", countryZh: "埃及" },
  { en: "Nairobi", zh: "内罗毕", country: "Kenya", countryZh: "肯尼亚" },
  { en: "Lagos", zh: "拉各斯", country: "Nigeria", countryZh: "尼日利亚" },
  { en: "Johannesburg", zh: "约翰内斯堡", country: "South Africa", countryZh: "南非" },
  { en: "Cape Town", zh: "开普敦", country: "South Africa", countryZh: "南非" },
  { en: "Casablanca", zh: "卡萨布兰卡", country: "Morocco", countryZh: "摩洛哥" },
  { en: "Athens", zh: "雅典", country: "Greece", countryZh: "希腊" },
  { en: "Rome", zh: "罗马", country: "Italy", countryZh: "意大利" },
  { en: "Milan", zh: "米兰", country: "Italy", countryZh: "意大利" },
  { en: "Venice", zh: "威尼斯", country: "Italy", countryZh: "意大利" },
  { en: "Madrid", zh: "马德里", country: "Spain", countryZh: "西班牙" },
  { en: "Barcelona", zh: "巴塞罗那", country: "Spain", countryZh: "西班牙" },
  { en: "Lisbon", zh: "里斯本", country: "Portugal", countryZh: "葡萄牙" },
  { en: "Paris", zh: "巴黎", country: "France", countryZh: "法国" },
  { en: "Lyon", zh: "里昂", country: "France", countryZh: "法国" },
  { en: "London", zh: "伦敦", country: "UK", countryZh: "英国" },
  { en: "Manchester", zh: "曼彻斯特", country: "UK", countryZh: "英国" },
  { en: "Edinburgh", zh: "爱丁堡", country: "UK", countryZh: "英国" },
  { en: "Dublin", zh: "都柏林", country: "Ireland", countryZh: "爱尔兰" },
  { en: "Amsterdam", zh: "阿姆斯特丹", country: "Netherlands", countryZh: "荷兰" },
  { en: "Brussels", zh: "布鲁塞尔", country: "Belgium", countryZh: "比利时" },
  { en: "Berlin", zh: "柏林", country: "Germany", countryZh: "德国" },
  { en: "Munich", zh: "慕尼黑", country: "Germany", countryZh: "德国" },
  { en: "Frankfurt", zh: "法兰克福", country: "Germany", countryZh: "德国" },
  { en: "Hamburg", zh: "汉堡", country: "Germany", countryZh: "德国" },
  { en: "Zurich", zh: "苏黎世", country: "Switzerland", countryZh: "瑞士" },
  { en: "Geneva", zh: "日内瓦", country: "Switzerland", countryZh: "瑞士" },
  { en: "Vienna", zh: "维也纳", country: "Austria", countryZh: "奥地利" },
  { en: "Prague", zh: "布拉格", country: "Czech Republic", countryZh: "捷克" },
  { en: "Warsaw", zh: "华沙", country: "Poland", countryZh: "波兰" },
  { en: "Budapest", zh: "布达佩斯", country: "Hungary", countryZh: "匈牙利" },
  { en: "Stockholm", zh: "斯德哥尔摩", country: "Sweden", countryZh: "瑞典" },
  { en: "Oslo", zh: "奥斯陆", country: "Norway", countryZh: "挪威" },
  { en: "Copenhagen", zh: "哥本哈根", country: "Denmark", countryZh: "丹麦" },
  { en: "Helsinki", zh: "赫尔辛基", country: "Finland", countryZh: "芬兰" },
  { en: "Reykjavik", zh: "雷克雅未克", country: "Iceland", countryZh: "冰岛" },
  { en: "Moscow", zh: "莫斯科", country: "Russia", countryZh: "俄罗斯" },
  { en: "Saint Petersburg", zh: "圣彼得堡", country: "Russia", countryZh: "俄罗斯" },
  { en: "Kyiv", zh: "基辅", country: "Ukraine", countryZh: "乌克兰" },
  { en: "New York", zh: "纽约", country: "USA", countryZh: "美国" },
  { en: "Los Angeles", zh: "洛杉矶", country: "USA", countryZh: "美国" },
  { en: "San Francisco", zh: "旧金山", country: "USA", countryZh: "美国" },
  { en: "Chicago", zh: "芝加哥", country: "USA", countryZh: "美国" },
  { en: "Boston", zh: "波士顿", country: "USA", countryZh: "美国" },
  { en: "Seattle", zh: "西雅图", country: "USA", countryZh: "美国" },
  { en: "Washington DC", zh: "华盛顿", country: "USA", countryZh: "美国" },
  { en: "Miami", zh: "迈阿密", country: "USA", countryZh: "美国" },
  { en: "Houston", zh: "休斯敦", country: "USA", countryZh: "美国" },
  { en: "Dallas", zh: "达拉斯", country: "USA", countryZh: "美国" },
  { en: "Las Vegas", zh: "拉斯维加斯", country: "USA", countryZh: "美国" },
  { en: "Honolulu", zh: "檀香山", country: "USA", countryZh: "美国" },
  { en: "Toronto", zh: "多伦多", country: "Canada", countryZh: "加拿大" },
  { en: "Vancouver", zh: "温哥华", country: "Canada", countryZh: "加拿大" },
  { en: "Montreal", zh: "蒙特利尔", country: "Canada", countryZh: "加拿大" },
  { en: "Mexico City", zh: "墨西哥城", country: "Mexico", countryZh: "墨西哥" },
  { en: "Havana", zh: "哈瓦那", country: "Cuba", countryZh: "古巴" },
  { en: "São Paulo", zh: "圣保罗", country: "Brazil", countryZh: "巴西" },
  { en: "Rio de Janeiro", zh: "里约热内卢", country: "Brazil", countryZh: "巴西" },
  { en: "Buenos Aires", zh: "布宜诺斯艾利斯", country: "Argentina", countryZh: "阿根廷" },
  { en: "Santiago", zh: "圣地亚哥", country: "Chile", countryZh: "智利" },
  { en: "Lima", zh: "利马", country: "Peru", countryZh: "秘鲁" },
  { en: "Bogotá", zh: "波哥大", country: "Colombia", countryZh: "哥伦比亚" },
  { en: "Sydney", zh: "悉尼", country: "Australia", countryZh: "澳大利亚" },
  { en: "Melbourne", zh: "墨尔本", country: "Australia", countryZh: "澳大利亚" },
  { en: "Brisbane", zh: "布里斯班", country: "Australia", countryZh: "澳大利亚" },
  { en: "Perth", zh: "珀斯", country: "Australia", countryZh: "澳大利亚" },
  { en: "Auckland", zh: "奥克兰", country: "New Zealand", countryZh: "新西兰" },
  { en: "Wellington", zh: "惠灵顿", country: "New Zealand", countryZh: "新西兰" },
];

export function searchCities(query: string, lang: "en" | "zh"): City[] {
  const q = query.trim().toLowerCase();
  if (!q) return CITIES.slice(0, 40);
  return CITIES.filter((c) => {
    return (
      c.en.toLowerCase().includes(q) ||
      c.zh.includes(query.trim()) ||
      c.country.toLowerCase().includes(q) ||
      c.countryZh.includes(query.trim())
    );
  }).slice(0, 60);
}

export function formatCity(c: City, lang: "en" | "zh"): string {
  return lang === "zh" ? `${c.zh}, ${c.countryZh}` : `${c.en}, ${c.country}`;
}
