import { createFileRoute } from "@tanstack/react-router";

import { useLang } from "@/lib/i18n";
import { LEGAL_CONTACT, legalCanonical, renderWithMailto } from "@/lib/legal";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Library of Destiny · 隐私政策" },
      {
        name: "description",
        content:
          "How Library of Destiny collects, uses, stores and protects your data — including birth details, generated readings and community content. 命运图书馆如何收集、使用、储存与保护你的资料。",
      },
      { property: "og:title", content: "Privacy Policy — Library of Destiny" },
      {
        property: "og:description",
        content: "Data we collect, why we collect it, and how to exercise your rights.",
      },
      { property: "og:type", content: "article" },
      { property: "og:url", content: legalCanonical("/privacy") },
    ],
    links: [{ rel: "canonical", href: legalCanonical("/privacy") }],
  }),
  component: PrivacyPage,
});

type Section = { h: string; body: string[] };
type Copy = {
  kicker: string;
  h1: string;
  effective: string;
  intro: string[];
  sections: Section[];
  contactHeading: string;
  contactBody: string[];
};

const EN: Copy = {
  kicker: "Legal",
  h1: "Privacy Policy",
  effective: `Effective date: ${LEGAL_CONTACT.effectiveDate}`,
  intro: [
    "This policy describes how Library of Destiny (\"we\", \"the library\") handles personal information you provide when you use the site, request a reading, save content, or contact us.",
    "We aim to collect only what a reading actually needs, to be honest about how AI is involved, and to give you real control over your data.",
  ],
  sections: [
    {
      h: "1. Information we collect",
      body: [
        "Birth details you enter into the ritual: full name (or nickname), date of birth, time of birth, place of birth (city / region) and time zone. These are required to compute an astrological chart.",
        "Account information when you sign in: email address, and optionally a display name and avatar. Registration sends a one-time verification link to your email — clicking it verifies the address and creates the account. Returning sign-in uses the same magic-link flow, and Google sign-in creates an account on first use and simply signs you in on subsequent visits. We never store passwords for you. Phone-number sign-in is not currently offered; if you signed in by phone in an earlier version, any historical phone number on your account is removed together with the rest of your data when you delete your account.",
        "Content you create: saved readings, questions you ask the AI companion, tarot draws, community posts, and messages sent through the \"elder\" companion or the feedback / bug-report flow.",
        "Technical data: IP address, browser type, device information and basic usage events (which pages you visit, when). We do not use third-party advertising trackers.",
      ],
    },
    {
      h: "2. Why we use your data",
      body: [
        "To compute your chart across four traditions (Western astrology, Vedic Jyotish, BaZi, Zi Wei Dou Shu) and produce your personalised reading.",
        "To let you sign in across devices, save readings, and return to them.",
        "To operate the AI companion (\"elder\"), the community, and to respond when you send feedback or a bug report.",
        "To keep the service secure, prevent abuse, and comply with legal obligations.",
      ],
    },
    {
      h: "3. AI processing and third parties",
      body: [
        "Readings and companion replies are generated by AI models running through our AI gateway. When you request a reading or send a message to the AI companion, the necessary inputs (for example your birth chart data or your question) are sent to the model provider that generates the response.",
        "Authentication, database and hosting are provided by our backend platform. Payments, when enabled, are handled by our payment provider — we do not store full card numbers.",
        "We do not sell your personal information. We do not share it with third parties for advertising.",
      ],
    },
    {
      h: "4. Retention",
      body: [
        "Account data and birth details are kept while your account exists. When you delete your account, they are removed as described in Section 7.",
        "Anonymous aggregated statistics (for example daily active users) may be retained after account deletion, because they no longer identify you.",
        "Backups may retain deleted content for a limited window (typically up to 30 days) before being overwritten.",
      ],
    },
    {
      h: "5. Security",
      body: [
        "Data is transmitted over TLS. Sign-in credentials are stored by our authentication provider using industry-standard protections. Access to production data is restricted to a small number of maintainers.",
        "No system is perfectly secure. If we become aware of a breach that affects you, we will notify you as required by applicable law.",
      ],
    },
    {
      h: "6. International transfers",
      body: [
        "The library may process data on servers outside your country of residence. Where required, we rely on standard contractual clauses or equivalent safeguards.",
      ],
    },
    {
      h: "7. Your rights",
      body: [
        "You may request access to, correction of, export of, or deletion of your personal data at any time. Deletion can be initiated directly from the /delete-account page or from the \"Privacy & data\" section of your account.",
        "Deletion removes your account, profile, birth details, saved readings, feedback, and community content you own, except records we are legally required to keep.",
        "You may also contact us at the address below to exercise these rights.",
      ],
    },
    {
      h: "8. Minors",
      body: [
        "This service is intended for adults. It is not directed at children under 16. If you are a parent or guardian and believe your child has provided personal data to us, please contact us and we will delete it.",
      ],
    },
    {
      h: "9. Changes to this policy",
      body: [
        "We may update this policy from time to time. Material changes will be signalled on this page and, where appropriate, by email. The date at the top of the page reflects the latest revision.",
      ],
    },
  ],
  contactHeading: "10. Contact",
  contactBody: [
    `Entity: ${LEGAL_CONTACT.entityName}`,
    `Email: ${LEGAL_CONTACT.privacyEmail}`,
  ],
};

const ZH: Copy = {
  kicker: "法律条款",
  h1: "隐私政策",
  effective: `生效日期：${LEGAL_CONTACT.effectiveDate}`,
  intro: [
    "本政策说明「命运图书馆」（下称「我们」「本馆」）在你使用本站、请求解读、保存内容或联系我们时，如何收集、使用与保护你的个人资料。",
    "我们只收集一次解读真正需要的信息，如实告知 AI 的参与方式，并为你保留对自己数据的完整控制权。",
  ],
  sections: [
    {
      h: "一、我们收集哪些资料",
      body: [
        "你在仪式中填写的出生资料：本名（或称呼）、出生日期、出生时间、出生地（城市 / 地区）及时区。这些是计算命盘的必要信息。",
        "账号资料：邮箱地址，以及可选的昵称与头像。注册时我们向邮箱寄出一次性验证链接，点击后即完成邮箱验证并创建账号；后续登录也走同一枚魔法链接；Google 登录则在首次授权时自动创建账号，之后直接登录。我们不保存你的密码。目前不再提供手机号登录；如你在旧版本以手机号登录，账户上残留的历史手机号会随删除账户一并清除。",
        "你创建的内容：保存的解读、向 AI 的追问、抽取的塔罗牌、社区帖子，以及通过「智者」树洞或反馈通道发送的消息。",
        "技术信息：IP 地址、浏览器与设备信息，以及基础使用事件（访问了哪些页面、访问时间）。我们不使用第三方广告追踪。",
      ],
    },
    {
      h: "二、我们如何使用这些资料",
      body: [
        "以四大体系（西方占星、印度吠陀、八字、紫微斗数）为你合成个性化解读。",
        "让你在不同设备上登录、保存与继续阅读你的报告。",
        "支持「智者」AI 陪伴、同门社区，以及在你反馈或报告问题时回应你。",
        "维护安全、防止滥用，并履行法律义务。",
      ],
    },
    {
      h: "三、AI 处理与第三方",
      body: [
        "解读与「智者」的回复由通过 AI 网关调用的 AI 模型生成。当你请求解读或与「智者」对话时，必要的输入（例如命盘数据或你的问题）会被发送至生成回复的模型提供商。",
        "登录、数据库与托管由我们的后端平台提供；如未来开通支付，支付将由支付服务商处理，我们不存储完整卡号。",
        "我们不出售你的个人资料，也不将其分享给第三方用于广告。",
      ],
    },
    {
      h: "四、保存期限",
      body: [
        "账号资料与出生信息在账户存在期间保留。你删除账户时，将按第七条所述被清除。",
        "已匿名化、聚合化的统计（如日活）在账户删除后仍可能保留，因为它们不再指向你个人。",
        "备份中可能在有限时间（通常不超过 30 天）内仍留有已删除内容的副本，之后会被覆盖。",
      ],
    },
    {
      h: "五、安全措施",
      body: [
        "数据以 TLS 加密传输，凭据由认证服务以行业通行方式保存。仅少数维护者可以访问生产数据。",
        "没有任何系统是绝对安全的。若发生涉及你的数据事件，我们将按适用法律的要求通知你。",
      ],
    },
    {
      h: "六、跨境处理",
      body: [
        "本馆的数据可能在你所在国家 / 地区之外的服务器上处理。如适用，我们依据标准合同条款或等效机制提供保障。",
      ],
    },
    {
      h: "七、你的权利",
      body: [
        "你可随时申请访问、更正、导出或删除自己的个人资料。你可以在 /delete-account 页面直接发起删除，或在账号中的「隐私与数据」区域操作。",
        "删除将清除你的账户、个人资料、出生信息、保存的解读、反馈以及你本人拥有的社区内容，法律要求保留者除外。",
        "你也可以通过下方联系方式联系我们以行使上述权利。",
      ],
    },
    {
      h: "八、未成年人",
      body: [
        "本服务面向成年人，并非面向 16 岁以下儿童。若你是家长或监护人，发现未成年人向我们提供了个人资料，请联系我们，我们会予以删除。",
      ],
    },
    {
      h: "九、政策更新",
      body: [
        "我们可能不时更新本政策。重大变更会在本页面提示，必要时通过邮件通知。页面顶部的日期反映最新修订。",
      ],
    },
  ],
  contactHeading: "十、联系我们",
  contactBody: [
    `主体：${LEGAL_CONTACT.entityName}`,
    `邮箱：${LEGAL_CONTACT.privacyEmail}`,
  ],
};

function PrivacyPage() {
  const { lang } = useLang();
  const c = lang === "zh" ? ZH : EN;
  return (
    <div className="mx-auto max-w-3xl px-6 pt-32 pb-32">
      <p className="mb-4 text-[10px] uppercase tracking-[0.42em] text-gold-dust">{c.kicker}</p>
      <h1 className="mb-4 font-serif text-4xl leading-tight text-stone-warm md:text-5xl">{c.h1}</h1>
      <p className="mb-10 text-[11px] uppercase tracking-[0.28em] text-stone-warm/50">{c.effective}</p>

      <div className="space-y-5 text-[15px] leading-relaxed text-stone-warm/80">
        {c.intro.map((p, i) => (
          <p key={i}>{p}</p>
        ))}
      </div>

      <div className="mt-12 space-y-10">
        {c.sections.map((s) => (
          <section key={s.h}>
            <h2 className="mb-3 font-serif text-2xl text-stone-warm">{s.h}</h2>
            <div className="space-y-3 text-[15px] leading-relaxed text-stone-warm/75">
              {s.body.map((p, i) => (
                <p key={i}>{p}</p>
              ))}
            </div>
          </section>
        ))}
        <section>
          <h2 className="mb-3 font-serif text-2xl text-stone-warm">{c.contactHeading}</h2>
          <div className="glass-card space-y-1 rounded-2xl p-5 text-[14px] text-stone-warm/80">
            {c.contactBody.map((line) => (
              <p key={line}>{renderWithMailto(line, LEGAL_CONTACT.privacyEmail)}</p>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
