/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraditionsRouteImport } from './routes/traditions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SynthesisRouteImport } from './routes/synthesis'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RitualRouteImport } from './routes/ritual'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LifeStudiesRouteImport } from './routes/life-studies'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LifeStudiesIndexRouteImport } from './routes/life-studies.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as LifeStudiesMathRouteImport } from './routes/life-studies.math'
import { Route as DevReaderHarnessRouteImport } from './routes/dev.reader-harness'
import { Route as DevPanoramaTourRouteImport } from './routes/dev.panorama-tour'
import { Route as DevGuidedLibraryV2RouteImport } from './routes/dev.guided-library-v2'
import { Route as DevDemoPremiumRouteImport } from './routes/dev.demo-premium'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiGenerateAvatarRouteImport } from './routes/api/generate-avatar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedMeSageRouteImport } from './routes/_authenticated/me.sage'
import { Route as AuthenticatedMeRelationshipsRouteImport } from './routes/_authenticated/me.relationships'
import { Route as AuthenticatedMeProfileRouteImport } from './routes/_authenticated/me.profile'
import { Route as AuthenticatedMeOracleRouteImport } from './routes/_authenticated/me.oracle'
import { Route as AuthenticatedMeMembershipRouteImport } from './routes/_authenticated/me.membership'
import { Route as AuthenticatedMeMatchRouteImport } from './routes/_authenticated/me.match'
import { Route as AuthenticatedMeLiteratureRouteImport } from './routes/_authenticated/me.literature'
import { Route as AuthenticatedMeHomeRouteImport } from './routes/_authenticated/me.home'
import { Route as AuthenticatedMeFriendsRouteImport } from './routes/_authenticated/me.friends'
import { Route as AuthenticatedMeEchoesRouteImport } from './routes/_authenticated/me.echoes'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const TraditionsRoute = TraditionsRouteImport.update({
  id: '/traditions',
  path: '/traditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SynthesisRoute = SynthesisRouteImport.update({
  id: '/synthesis',
  path: '/synthesis',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualRoute = RitualRouteImport.update({
  id: '/ritual',
  path: '/ritual',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeStudiesRoute = LifeStudiesRouteImport.update({
  id: '/life-studies',
  path: '/life-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeStudiesIndexRoute = LifeStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LifeStudiesRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const LifeStudiesMathRoute = LifeStudiesMathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => LifeStudiesRoute,
} as any)
const DevReaderHarnessRoute = DevReaderHarnessRouteImport.update({
  id: '/dev/reader-harness',
  path: '/dev/reader-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPanoramaTourRoute = DevPanoramaTourRouteImport.update({
  id: '/dev/panorama-tour',
  path: '/dev/panorama-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGuidedLibraryV2Route = DevGuidedLibraryV2RouteImport.update({
  id: '/dev/guided-library-v2',
  path: '/dev/guided-library-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDemoPremiumRoute = DevDemoPremiumRouteImport.update({
  id: '/dev/demo-premium',
  path: '/dev/demo-premium',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiGenerateAvatarRoute = ApiGenerateAvatarRouteImport.update({
  id: '/api/generate-avatar',
  path: '/api/generate-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMeSageRoute = AuthenticatedMeSageRouteImport.update({
  id: '/me/sage',
  path: '/me/sage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRelationshipsRoute =
  AuthenticatedMeRelationshipsRouteImport.update({
    id: '/me/relationships',
    path: '/me/relationships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeProfileRoute = AuthenticatedMeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeOracleRoute = AuthenticatedMeOracleRouteImport.update({
  id: '/me/oracle',
  path: '/me/oracle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeMembershipRoute =
  AuthenticatedMeMembershipRouteImport.update({
    id: '/me/membership',
    path: '/me/membership',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeMatchRoute = AuthenticatedMeMatchRouteImport.update({
  id: '/me/match',
  path: '/me/match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeLiteratureRoute =
  AuthenticatedMeLiteratureRouteImport.update({
    id: '/me/literature',
    path: '/me/literature',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeHomeRoute = AuthenticatedMeHomeRouteImport.update({
  id: '/me/home',
  path: '/me/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeFriendsRoute = AuthenticatedMeFriendsRouteImport.update({
  id: '/me/friends',
  path: '/me/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeEchoesRoute = AuthenticatedMeEchoesRouteImport.update({
  id: '/me/echoes',
  path: '/me/echoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/delete-account': typeof DeleteAccountRoute
  '/life-studies': typeof LifeStudiesRouteWithChildren
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/ritual': typeof RitualRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthesis': typeof SynthesisRoute
  '/terms': typeof TermsRoute
  '/traditions': typeof TraditionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/generate-avatar': typeof ApiGenerateAvatarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/dev/demo-premium': typeof DevDemoPremiumRoute
  '/dev/guided-library-v2': typeof DevGuidedLibraryV2Route
  '/dev/panorama-tour': typeof DevPanoramaTourRoute
  '/dev/reader-harness': typeof DevReaderHarnessRoute
  '/life-studies/math': typeof LifeStudiesMathRoute
  '/auth/': typeof AuthIndexRoute
  '/life-studies/': typeof LifeStudiesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/me/echoes': typeof AuthenticatedMeEchoesRoute
  '/me/friends': typeof AuthenticatedMeFriendsRoute
  '/me/home': typeof AuthenticatedMeHomeRoute
  '/me/literature': typeof AuthenticatedMeLiteratureRoute
  '/me/match': typeof AuthenticatedMeMatchRoute
  '/me/membership': typeof AuthenticatedMeMembershipRoute
  '/me/oracle': typeof AuthenticatedMeOracleRoute
  '/me/profile': typeof AuthenticatedMeProfileRoute
  '/me/relationships': typeof AuthenticatedMeRelationshipsRoute
  '/me/sage': typeof AuthenticatedMeSageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/delete-account': typeof DeleteAccountRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/ritual': typeof RitualRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthesis': typeof SynthesisRoute
  '/terms': typeof TermsRoute
  '/traditions': typeof TraditionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/generate-avatar': typeof ApiGenerateAvatarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/dev/demo-premium': typeof DevDemoPremiumRoute
  '/dev/guided-library-v2': typeof DevGuidedLibraryV2Route
  '/dev/panorama-tour': typeof DevPanoramaTourRoute
  '/dev/reader-harness': typeof DevReaderHarnessRoute
  '/life-studies/math': typeof LifeStudiesMathRoute
  '/auth': typeof AuthIndexRoute
  '/life-studies': typeof LifeStudiesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/me/echoes': typeof AuthenticatedMeEchoesRoute
  '/me/friends': typeof AuthenticatedMeFriendsRoute
  '/me/home': typeof AuthenticatedMeHomeRoute
  '/me/literature': typeof AuthenticatedMeLiteratureRoute
  '/me/match': typeof AuthenticatedMeMatchRoute
  '/me/membership': typeof AuthenticatedMeMembershipRoute
  '/me/oracle': typeof AuthenticatedMeOracleRoute
  '/me/profile': typeof AuthenticatedMeProfileRoute
  '/me/relationships': typeof AuthenticatedMeRelationshipsRoute
  '/me/sage': typeof AuthenticatedMeSageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/delete-account': typeof DeleteAccountRoute
  '/life-studies': typeof LifeStudiesRouteWithChildren
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/ritual': typeof RitualRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthesis': typeof SynthesisRoute
  '/terms': typeof TermsRoute
  '/traditions': typeof TraditionsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/generate-avatar': typeof ApiGenerateAvatarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/dev/demo-premium': typeof DevDemoPremiumRoute
  '/dev/guided-library-v2': typeof DevGuidedLibraryV2Route
  '/dev/panorama-tour': typeof DevPanoramaTourRoute
  '/dev/reader-harness': typeof DevReaderHarnessRoute
  '/life-studies/math': typeof LifeStudiesMathRoute
  '/auth/': typeof AuthIndexRoute
  '/life-studies/': typeof LifeStudiesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/me/echoes': typeof AuthenticatedMeEchoesRoute
  '/_authenticated/me/friends': typeof AuthenticatedMeFriendsRoute
  '/_authenticated/me/home': typeof AuthenticatedMeHomeRoute
  '/_authenticated/me/literature': typeof AuthenticatedMeLiteratureRoute
  '/_authenticated/me/match': typeof AuthenticatedMeMatchRoute
  '/_authenticated/me/membership': typeof AuthenticatedMeMembershipRoute
  '/_authenticated/me/oracle': typeof AuthenticatedMeOracleRoute
  '/_authenticated/me/profile': typeof AuthenticatedMeProfileRoute
  '/_authenticated/me/relationships': typeof AuthenticatedMeRelationshipsRoute
  '/_authenticated/me/sage': typeof AuthenticatedMeSageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/community'
    | '/delete-account'
    | '/life-studies'
    | '/mcp'
    | '/privacy'
    | '/report'
    | '/ritual'
    | '/sitemap.xml'
    | '/synthesis'
    | '/terms'
    | '/traditions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/api/generate-avatar'
    | '/auth/callback'
    | '/auth/reset'
    | '/dev/demo-premium'
    | '/dev/guided-library-v2'
    | '/dev/panorama-tour'
    | '/dev/reader-harness'
    | '/life-studies/math'
    | '/auth/'
    | '/life-studies/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/me/echoes'
    | '/me/friends'
    | '/me/home'
    | '/me/literature'
    | '/me/match'
    | '/me/membership'
    | '/me/oracle'
    | '/me/profile'
    | '/me/relationships'
    | '/me/sage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/delete-account'
    | '/mcp'
    | '/privacy'
    | '/report'
    | '/ritual'
    | '/sitemap.xml'
    | '/synthesis'
    | '/terms'
    | '/traditions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/api/generate-avatar'
    | '/auth/callback'
    | '/auth/reset'
    | '/dev/demo-premium'
    | '/dev/guided-library-v2'
    | '/dev/panorama-tour'
    | '/dev/reader-harness'
    | '/life-studies/math'
    | '/auth'
    | '/life-studies'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/me/echoes'
    | '/me/friends'
    | '/me/home'
    | '/me/literature'
    | '/me/match'
    | '/me/membership'
    | '/me/oracle'
    | '/me/profile'
    | '/me/relationships'
    | '/me/sage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/community'
    | '/delete-account'
    | '/life-studies'
    | '/mcp'
    | '/privacy'
    | '/report'
    | '/ritual'
    | '/sitemap.xml'
    | '/synthesis'
    | '/terms'
    | '/traditions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/api/generate-avatar'
    | '/auth/callback'
    | '/auth/reset'
    | '/dev/demo-premium'
    | '/dev/guided-library-v2'
    | '/dev/panorama-tour'
    | '/dev/reader-harness'
    | '/life-studies/math'
    | '/auth/'
    | '/life-studies/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/me/echoes'
    | '/_authenticated/me/friends'
    | '/_authenticated/me/home'
    | '/_authenticated/me/literature'
    | '/_authenticated/me/match'
    | '/_authenticated/me/membership'
    | '/_authenticated/me/oracle'
    | '/_authenticated/me/profile'
    | '/_authenticated/me/relationships'
    | '/_authenticated/me/sage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  LifeStudiesRoute: typeof LifeStudiesRouteWithChildren
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  RitualRoute: typeof RitualRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SynthesisRoute: typeof SynthesisRoute
  TermsRoute: typeof TermsRoute
  TraditionsRoute: typeof TraditionsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiGenerateAvatarRoute: typeof ApiGenerateAvatarRoute
  DevDemoPremiumRoute: typeof DevDemoPremiumRoute
  DevGuidedLibraryV2Route: typeof DevGuidedLibraryV2Route
  DevPanoramaTourRoute: typeof DevPanoramaTourRoute
  DevReaderHarnessRoute: typeof DevReaderHarnessRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traditions': {
      id: '/traditions'
      path: '/traditions'
      fullPath: '/traditions'
      preLoaderRoute: typeof TraditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthesis': {
      id: '/synthesis'
      path: '/synthesis'
      fullPath: '/synthesis'
      preLoaderRoute: typeof SynthesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritual': {
      id: '/ritual'
      path: '/ritual'
      fullPath: '/ritual'
      preLoaderRoute: typeof RitualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-studies': {
      id: '/life-studies'
      path: '/life-studies'
      fullPath: '/life-studies'
      preLoaderRoute: typeof LifeStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-studies/': {
      id: '/life-studies/'
      path: '/'
      fullPath: '/life-studies/'
      preLoaderRoute: typeof LifeStudiesIndexRouteImport
      parentRoute: typeof LifeStudiesRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/life-studies/math': {
      id: '/life-studies/math'
      path: '/math'
      fullPath: '/life-studies/math'
      preLoaderRoute: typeof LifeStudiesMathRouteImport
      parentRoute: typeof LifeStudiesRoute
    }
    '/dev/reader-harness': {
      id: '/dev/reader-harness'
      path: '/dev/reader-harness'
      fullPath: '/dev/reader-harness'
      preLoaderRoute: typeof DevReaderHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/panorama-tour': {
      id: '/dev/panorama-tour'
      path: '/dev/panorama-tour'
      fullPath: '/dev/panorama-tour'
      preLoaderRoute: typeof DevPanoramaTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/guided-library-v2': {
      id: '/dev/guided-library-v2'
      path: '/dev/guided-library-v2'
      fullPath: '/dev/guided-library-v2'
      preLoaderRoute: typeof DevGuidedLibraryV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/demo-premium': {
      id: '/dev/demo-premium'
      path: '/dev/demo-premium'
      fullPath: '/dev/demo-premium'
      preLoaderRoute: typeof DevDemoPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/generate-avatar': {
      id: '/api/generate-avatar'
      path: '/api/generate-avatar'
      fullPath: '/api/generate-avatar'
      preLoaderRoute: typeof ApiGenerateAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me/sage': {
      id: '/_authenticated/me/sage'
      path: '/me/sage'
      fullPath: '/me/sage'
      preLoaderRoute: typeof AuthenticatedMeSageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/relationships': {
      id: '/_authenticated/me/relationships'
      path: '/me/relationships'
      fullPath: '/me/relationships'
      preLoaderRoute: typeof AuthenticatedMeRelationshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/profile': {
      id: '/_authenticated/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof AuthenticatedMeProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/oracle': {
      id: '/_authenticated/me/oracle'
      path: '/me/oracle'
      fullPath: '/me/oracle'
      preLoaderRoute: typeof AuthenticatedMeOracleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/membership': {
      id: '/_authenticated/me/membership'
      path: '/me/membership'
      fullPath: '/me/membership'
      preLoaderRoute: typeof AuthenticatedMeMembershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/match': {
      id: '/_authenticated/me/match'
      path: '/me/match'
      fullPath: '/me/match'
      preLoaderRoute: typeof AuthenticatedMeMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/literature': {
      id: '/_authenticated/me/literature'
      path: '/me/literature'
      fullPath: '/me/literature'
      preLoaderRoute: typeof AuthenticatedMeLiteratureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/home': {
      id: '/_authenticated/me/home'
      path: '/me/home'
      fullPath: '/me/home'
      preLoaderRoute: typeof AuthenticatedMeHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/friends': {
      id: '/_authenticated/me/friends'
      path: '/me/friends'
      fullPath: '/me/friends'
      preLoaderRoute: typeof AuthenticatedMeFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/echoes': {
      id: '/_authenticated/me/echoes'
      path: '/me/echoes'
      fullPath: '/me/echoes'
      preLoaderRoute: typeof AuthenticatedMeEchoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeEchoesRoute: typeof AuthenticatedMeEchoesRoute
  AuthenticatedMeFriendsRoute: typeof AuthenticatedMeFriendsRoute
  AuthenticatedMeHomeRoute: typeof AuthenticatedMeHomeRoute
  AuthenticatedMeLiteratureRoute: typeof AuthenticatedMeLiteratureRoute
  AuthenticatedMeMatchRoute: typeof AuthenticatedMeMatchRoute
  AuthenticatedMeMembershipRoute: typeof AuthenticatedMeMembershipRoute
  AuthenticatedMeOracleRoute: typeof AuthenticatedMeOracleRoute
  AuthenticatedMeProfileRoute: typeof AuthenticatedMeProfileRoute
  AuthenticatedMeRelationshipsRoute: typeof AuthenticatedMeRelationshipsRoute
  AuthenticatedMeSageRoute: typeof AuthenticatedMeSageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeEchoesRoute: AuthenticatedMeEchoesRoute,
  AuthenticatedMeFriendsRoute: AuthenticatedMeFriendsRoute,
  AuthenticatedMeHomeRoute: AuthenticatedMeHomeRoute,
  AuthenticatedMeLiteratureRoute: AuthenticatedMeLiteratureRoute,
  AuthenticatedMeMatchRoute: AuthenticatedMeMatchRoute,
  AuthenticatedMeMembershipRoute: AuthenticatedMeMembershipRoute,
  AuthenticatedMeOracleRoute: AuthenticatedMeOracleRoute,
  AuthenticatedMeProfileRoute: AuthenticatedMeProfileRoute,
  AuthenticatedMeRelationshipsRoute: AuthenticatedMeRelationshipsRoute,
  AuthenticatedMeSageRoute: AuthenticatedMeSageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetRoute: AuthResetRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LifeStudiesRouteChildren {
  LifeStudiesMathRoute: typeof LifeStudiesMathRoute
  LifeStudiesIndexRoute: typeof LifeStudiesIndexRoute
}

const LifeStudiesRouteChildren: LifeStudiesRouteChildren = {
  LifeStudiesMathRoute: LifeStudiesMathRoute,
  LifeStudiesIndexRoute: LifeStudiesIndexRoute,
}

const LifeStudiesRouteWithChildren = LifeStudiesRoute._addFileChildren(
  LifeStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  CommunityRoute: CommunityRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  LifeStudiesRoute: LifeStudiesRouteWithChildren,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  RitualRoute: RitualRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SynthesisRoute: SynthesisRoute,
  TermsRoute: TermsRoute,
  TraditionsRoute: TraditionsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiGenerateAvatarRoute: ApiGenerateAvatarRoute,
  DevDemoPremiumRoute: DevDemoPremiumRoute,
  DevGuidedLibraryV2Route: DevGuidedLibraryV2Route,
  DevPanoramaTourRoute: DevPanoramaTourRoute,
  DevReaderHarnessRoute: DevReaderHarnessRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
