/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraditionsRouteImport } from './routes/traditions'
import { Route as SynthesisRouteImport } from './routes/synthesis'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RitualRouteImport } from './routes/ritual'
import { Route as ReportRouteImport } from './routes/report'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateAvatarRouteImport } from './routes/api/generate-avatar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TraditionsRoute = TraditionsRouteImport.update({
  id: '/traditions',
  path: '/traditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SynthesisRoute = SynthesisRouteImport.update({
  id: '/synthesis',
  path: '/synthesis',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualRoute = RitualRouteImport.update({
  id: '/ritual',
  path: '/ritual',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAvatarRoute = ApiGenerateAvatarRouteImport.update({
  id: '/api/generate-avatar',
  path: '/api/generate-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/report': typeof ReportRoute
  '/ritual': typeof RitualRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthesis': typeof SynthesisRoute
  '/traditions': typeof TraditionsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/generate-avatar': typeof ApiGenerateAvatarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/report': typeof ReportRoute
  '/ritual': typeof RitualRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthesis': typeof SynthesisRoute
  '/traditions': typeof TraditionsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/generate-avatar': typeof ApiGenerateAvatarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/report': typeof ReportRoute
  '/ritual': typeof RitualRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthesis': typeof SynthesisRoute
  '/traditions': typeof TraditionsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/generate-avatar': typeof ApiGenerateAvatarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/community'
    | '/report'
    | '/ritual'
    | '/sitemap.xml'
    | '/synthesis'
    | '/traditions'
    | '/admin'
    | '/api/generate-avatar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/community'
    | '/report'
    | '/ritual'
    | '/sitemap.xml'
    | '/synthesis'
    | '/traditions'
    | '/admin'
    | '/api/generate-avatar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/community'
    | '/report'
    | '/ritual'
    | '/sitemap.xml'
    | '/synthesis'
    | '/traditions'
    | '/_authenticated/admin'
    | '/api/generate-avatar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ReportRoute: typeof ReportRoute
  RitualRoute: typeof RitualRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SynthesisRoute: typeof SynthesisRoute
  TraditionsRoute: typeof TraditionsRoute
  ApiGenerateAvatarRoute: typeof ApiGenerateAvatarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traditions': {
      id: '/traditions'
      path: '/traditions'
      fullPath: '/traditions'
      preLoaderRoute: typeof TraditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthesis': {
      id: '/synthesis'
      path: '/synthesis'
      fullPath: '/synthesis'
      preLoaderRoute: typeof SynthesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritual': {
      id: '/ritual'
      path: '/ritual'
      fullPath: '/ritual'
      preLoaderRoute: typeof RitualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-avatar': {
      id: '/api/generate-avatar'
      path: '/api/generate-avatar'
      fullPath: '/api/generate-avatar'
      preLoaderRoute: typeof ApiGenerateAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ReportRoute: ReportRoute,
  RitualRoute: RitualRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SynthesisRoute: SynthesisRoute,
  TraditionsRoute: TraditionsRoute,
  ApiGenerateAvatarRoute: ApiGenerateAvatarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
